### ISSUE TITLE
no colors in response after use send request button

### ISSUE THREAD

**Issue by Grubhart** [jyapurv/manifest#1]
When use send request button, the input and output texto box should show formatted json strings and highlighted

**Comment by develozombie** [comment]
Thanks for notice the bug, please send your PR for review

**Comment by cesarfong** [comment]
success: function (data) {
                $('#end').text(prettyFy(data));
                hljs.highlightBlock(document.getElementById("end"));

**Comment by develozombie** [comment]
Bug fixed

**Comment by Grubhart** [comment]
it works!! thanks @cesarfong !!!
Closing issue
